config/routes.rb
Vinus::Engine.routes.draw do
  get 'attachment/:id/:filename.:extension' => 'attachments#show'

  resources :customers do
    post :search, on: :collection
    resources :addresses
  end

  resources :merchants

  resources :vendors do
    resources :localisations, controller: 'vendor_localisations'
  end

  resources :product_categories do
    resources :localisations, controller: 'product_category_localisations'
  end

  resources :products do
    resources :variants
    resources :localisations, controller: 'product_localisations'
    collection do
      get :import
      post :import
    end
  end

  resources :orders do
    collection do
      post :search
    end
    member do
      post :accept
      post :reject
      post :ship
      get :despatch_note
    end
    resources :payments, only: [:create, :destroy] do
      match :refund, on: :member, via: [:get, :post]
    end
  end

  resources :stock_level_adjustments, only: [:index, :create]

  resources :delivery_services do
    resources :delivery_service_prices
  end

  resources :tax_rates
  resources :users
  resources :countries
  resources :attachments, only: :destroy

  get 'settings' => 'settings#edit'
  post 'settings' => 'settings#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  get 'login/reset' => 'password_resets#new'
  post 'login/reset' => 'password_resets#create'

  delete 'logout' => 'sessions#destroy'
  root to: 'dashboard#home'
end

app/models/vinus/address.rb
module Vinus
  class Address < ActiveRecord::Base
    # An array of all the available types for an address
    TYPES = %w(billing delivery).freeze

    # Set the table name
    self.table_name = 'vinus_addresses'

    # The customer which this address should be linked to
    #
    # @return [Vinus::Customer]
    belongs_to :customer, class_name: 'Vinus::Customer'

    # The order which this address should be linked to
    #
    # @return [Vinus::Order]
    belongs_to :order, class_name: 'Vinus::Order'

    # The country which this address should be linked to
    #
    # @return [Vinus::Country]
    belongs_to :country, class_name: 'Vinus::Country'

    # Validations
    validates :address_type, presence: true, inclusion: { in: TYPES }
    validates :address1, presence: true
    validates :address3, presence: true
    validates :address4, presence: true
    validates :postcode, presence: true
    validates :country, presence: true

    # All addresses ordered by their id asending
    scope :ordered, -> { order(id: :desc) }
    scope :default, -> { where(default: true) }
    scope :billing, -> { where(address_type: 'billing') }
    scope :delivery, -> { where(address_type: 'delivery') }

    def full_address
      [address1, address2, address3, address4, postcode, country.try(:name)].join(', ')
    end
  end
end

app/models/vinus/attachment.rb
module Vinus
  class Attachment < ActiveRecord::Base
    # Set the table name
    self.table_name = 'vinus_attachments'

    # Mount the Carrierwave uploader
    mount_uploader :file, AttachmentUploader

    # Relationships
    belongs_to :parent, polymorphic: true

    # Validations
    validates :file_name, presence: true
    validates :file_type, presence: true
    validates :file_size, presence: true
    validates :file, presence: true
    validates :token, presence: true, uniqueness: true

    # All attachments should have a token assigned to this
    before_validation { self.token = SecureRandom.uuid if token.blank? }

    # Set the appropriate values in the model
    before_validation do
      if file
        self.file_name = file.filename if file_name.blank?
        self.file_type = file.content_type if file_type.blank?
        self.file_size = file.size if file_size.blank?
      end
    end

    # Return the attachment for a given role
    def self.for(role)
      where(role: role).first
    end

    # Return the path to the attachment
    def path
      file.url
    end

    # Is the attachment an image?
    def image?
      file_type.match(/\Aimage\//).present?
    end
  end
end

app/models/vinus/country.rb
module Vinus
  # The Vinus::Country model stores countries which can be used for delivery & billing
  # addresses for orders.
  #
  # You can use the Vinus::CountryImporter to import a pre-defined list of countries
  # into your database. This automatically happens when you run the 'vinus:setup'
  # rake task.

  class Country < ActiveRecord::Base
    self.table_name = 'vinus_countries'

    # All orders which have this country set as their billing country
    has_many :billed_orders, dependent: :restrict_with_exception, class_name: 'Vinus::Order', foreign_key: 'billing_country_id'

    # All orders which have this country set as their delivery country
    has_many :delivered_orders, dependent: :restrict_with_exception, class_name: 'Vinus::Order', foreign_key: 'delivery_country_id'

    # All countries ordered by their name asending
    scope :ordered, -> { order(name: :asc) }

    # Validations
    validates :name, presence: true
  end
end

app/models/vinus/customer.rb
module Vinus
  class Customer < ActiveRecord::Base
    EMAIL_REGEX = /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i
    PHONE_REGEX = /\A[+?\d\ \-x\(\)]{7,}\z/

    self.table_name = 'vinus_customers'

    has_many :addresses, dependent: :restrict_with_exception, class_name: 'Vinus::Address'

    has_many :orders, dependent: :restrict_with_exception, class_name: 'Vinus::Order'

    # Validations
    validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }
    validates :phone, presence: true, format: { with: PHONE_REGEX }

    # All customers ordered by their ID desending
    scope :ordered, -> { order(id: :desc) }

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    def self.ransackable_attributes(_auth_object = nil)
      %w(id first_name last_name company email phone mobile) + _ransackers.keys
    end

    def self.ransackable_associations(_auth_object = nil)
      []
    end
  end
end

app/models/vinus/delivery_service.rb
module Vinus
  class DeliveryService < ActiveRecord::Base
    self.table_name = 'vinus_delivery_services'

    # Validations
    validates :name, presence: true
    validates :courier, presence: true

    # Orders which are assigned to this delivery service
    has_many :orders, dependent: :restrict_with_exception, class_name: 'Vinus::Order'

    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, dependent: :destroy, class_name: 'Vinus::DeliveryServicePrice'

    # All active delivery services
    scope :active, -> { where(active: true) }

    # Returns a tracking URL for the passed order
    #
    # @param order [Vinus::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!('{{consignment_number}}', CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!('{{delivery_postcode}}', CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!('{{billing_postcode}}', CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end
  end
end

app/models/vinus/delivery_service_price.rb
module Vinus
  class DeliveryServicePrice < ActiveRecord::Base
    # Set the table name
    self.table_name = 'vinus_delivery_service_prices'

    include Vinus::AssociatedCountries

    # The delivery service which this price belongs to
    belongs_to :delivery_service, class_name: 'Vinus::DeliveryService'

    # The tax rate which should be applied
    belongs_to :tax_rate, class_name: 'Vinus::TaxRate'

    # Validations
    validates :code, presence: true
    validates :price, numericality: true
    validates :cost_price, numericality: true, allow_blank: true
    validates :min_weight, numericality: true
    validates :max_weight, numericality: true

    # All prices ordered by their price ascending
    scope :ordered, -> { order(price: :asc) }

    # All prices which are suitable for the weight passed.
    #
    # @param weight [BigDecimal] the weight of the order
    scope :for_weight, -> (weight) { where('min_weight <= ? AND max_weight >= ?', weight, weight) }
  end
end

app/models/vinus/merchant.rb
module Vinus
  class Merchant < ActiveRecord::Base
    self.table_name = 'vinus_merchants'
    has_many :vendors, dependent: :destroy, class_name: 'Vinus::Vendor', inverse_of: :vendor
  end
end

app/models/vinus/order/packages.rb
module Vinus
  class Order < ActiveRecord::Base
    def package_items!
      self.vendors.each do |vendor|
        package = self.packages.build(vendor: vendor)
        package.save!
      end
    end
  end
end

app/models/vinus/product.rb
require 'roo'
require 'globalize'

module Vinus
  class Product < ActiveRecord::Base
    self.table_name = 'vinus_products'

    # Add dependencies for products
    require_dependency 'vinus/product/product_attributes'
    require_dependency 'vinus/product/variants'

    # Attachments for this product
    has_many :attachments, as: :parent, dependent: :destroy, autosave: true, class_name: 'Vinus::Attachment'

    # The product's categorizations
    #
    # @return [Vinus::ProductCategorization]
    has_many :product_categorizations, dependent: :destroy, class_name: 'Vinus::ProductCategorization', inverse_of: :product
    # The product's categories
    #
    # @return [Vinus::ProductCategory]
    has_many :product_categories, class_name: 'Vinus::ProductCategory', through: :product_categorizations

    # The product's tax rate
    #
    # @return [Vinus::TaxRate]
    belongs_to :tax_rate, class_name: 'Vinus::TaxRate'

    # Ordered items which are associated with this product
    has_many :order_items, dependent: :restrict_with_exception, class_name: 'Vinus::OrderItem', as: :ordered_item

    # Orders which have ordered this product
    has_many :orders, through: :order_items, class_name: 'Vinus::Order'

    # Stock level adjustments for this product
    has_many :stock_level_adjustments, dependent: :destroy, class_name: 'Vinus::StockLevelAdjustment', as: :item

    # The vendor which this product should be linked to
    #
    # @return [Vinus::Vendor]
    belongs_to :vendor, class_name: 'Vinus::Vendor'

    has_one :merchant, class_name: 'Vinus::Merchant', through: :vendor

    # Validations
    with_options if: proc { |p| p.parent.nil? } do |product|
      product.validate :has_at_least_one_product_category
      product.validates :description, presence: true
      product.validates :short_description, presence: true
    end
    validates :name, presence: true
    validates :permalink, presence: true, uniqueness: true, permalink: true
    validates :sku, presence: true
    validates :weight, numericality: true
    validates :price, numericality: true
    validates :cost_price, numericality: true, allow_blank: true

    # Before validation, set the permalink if we don't already have one
    before_validation { self.permalink = name.parameterize if permalink.blank? && name.is_a?(String) }

    # All active products
    scope :active, -> { where(active: true) }

    # All featured products
    scope :featured, -> { where(featured: true) }

    # Localisations
    translates :name, :permalink, :description, :short_description
    scope :ordered, -> { includes(:translations).order(:name) }

    def attachments=(attrs)
      if attrs['default_image']['file'].present? then attachments.build(attrs['default_image']) end
      if attrs['data_sheet']['file'].present? then attachments.build(attrs['data_sheet']) end

      if attrs['extra']['file'].present? then attrs['extra']['file'].each { |attr| attachments.build(file: attr, parent_id: attrs['extra']['parent_id'], parent_type: attrs['extra']['parent_type']) } end
    end

    # Return the name of the product
    #
    # @return [String]
    def full_name
      parent ? "#{parent.name} (#{name})" : name
    end

    # Is this product orderable?
    #
    # @return [Boolean]
    def orderable?
      return false unless active?
      return false if has_variants?
      true
    end

    # The tax rate for the product
    #
    # @return [BigDecimal]
    def rate
      default_variant ? default_variant.tax_rate.rate : tax_rate.rate
    end

    # The full price for the product (with tax)
    #
    # @return [BigDecimal]
    def full_price
      price * (rate / BigDecimal(100) + 1) || BigDecimal(0)
    end
    # alias_method :price_with_tax, :full_price

    # The price for the product
    #
    # @return [BigDecimal]
    def price
      # self.default_variant ? self.default_variant.price : read_attribute(:price)
      default_variant ? default_variant.price : read_attribute(:price)
    end

    # Is this product currently in stock?
    #
    # @return [Boolean]
    def in_stock?
      default_variant ? default_variant.in_stock? : (stock_control? ? stock > 0 : true)
    end

    # Return the total number of items currently in stock
    #
    # @return [Fixnum]
    def stock
      stock_level_adjustments.sum(:adjustment)
    end

    # Return the first product category
    #
    # @return [Vinus::ProductCategory]
    def product_category
      product_categories.first
    rescue
      nil
    end

    # Return attachment for the default_image role
    #
    # @return [String]
    def default_image
      attachments.for('default_image')
    end

    # Set attachment for the default_image role
    def default_image_file=(file)
      attachments.build(file: file, role: 'default_image')
    end

    # Return attachment for the data_sheet role
    #
    # @return [String]
    def data_sheet
      attachments.for('data_sheet')
    end

    # Search for products which include the given attributes and return an active record
    # scope of these products. Chainable with other scopes and with_attributes methods.
    # For example:
    #
    #   Vinus::Product.active.with_attribute('Manufacturer', 'Apple').with_attribute('Model', ['Macbook', 'iPhone'])
    #
    # @return [Enumerable]
    def self.with_attributes(key, values)
      product_ids = Vinus::ProductAttribute.searchable.where(key: key, value: values).pluck(:product_id).uniq
      where(id: product_ids)
    end

    # Imports products from a spreadsheet file
    # Example:
    #
    #   Vinus:Product.import("path/to/file.csv")
    def self.import(file)
      spreadsheet = open_spreadsheet(file)
      spreadsheet.default_sheet = spreadsheet.sheets.first
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).each do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]

        # Don't import products where the name is blank
        next if row['name'].nil?
        if product = where(name: row['name']).take
          # Dont import products with the same name but update quantities
          qty = row['qty'].to_i
          if qty > 0
            product.stock_level_adjustments.create!(description: I18n.t('vinus.import'), adjustment: qty)
          end
        else
          product = new
          product.name = row['name']
          product.sku = row['sku']
          product.description = row['description']
          product.short_description = row['short_description']
          product.weight = row['weight']
          product.price = row['price'].nil? ? 0 : row['price']
          product.permalink = row['permalink']

          product.product_categories << begin
            Vinus::ProductCategory.find_or_initialize_by(name: row['category_name'])
          end

          product.save!

          qty = row['qty'].to_i
          if qty > 0
            product.stock_level_adjustments.create!(description: I18n.t('vinus.import'), adjustment: qty)
          end
        end
      end
    end

    def self.open_spreadsheet(file)
      case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xls' then Roo::Excel.new(file.path)
      when '.xlsx' then Roo::Excelx.new(file.path)
      else fail I18n.t('vinus.imports.errors.unknown_format', filename: File.original_filename)
      end
    end

    private

    # Validates

    def has_at_least_one_product_category
      errors.add(:base, 'must add at least one product category') if product_categories.blank?
    end
  end
end

app/models/vinus/product/product_attributes.rb
module Vinus
  class Product < ActiveRecord::Base
    # Product attributes for this product
    has_many :product_attributes, -> { order(:position) }, class_name: 'Vinus::ProductAttribute'

    # Used for setting an array of product attributes which will be updated. Usually
    # received from a web browser.
    attr_accessor :product_attributes_array

    # After saving automatically try to update the product attributes based on the
    # the contents of the product_attributes_array array.
    after_save do
      if product_attributes_array.is_a?(Array)
        product_attributes.update_from_array(product_attributes_array)
      end
    end
  end
end

app/views/vinus/products/_form.html.haml
= form_for @product, :html => {:multipart => true} do |f|
  = f.error_messages
  = field_set_tag  t('vinus.products.product_information') do
    .splitContainer
      %dl.half
        %dt= f.label :product_categories, t('vinus.product_category.product_categories')
        %dd= f.collection_select :product_category_ids, Vinus::ProductCategory.ordered, :id, :name, {:prompt => false}, {:class => 'chosen', :multiple => true, :data => {:placeholder => t('vinus.product_category.choose_product_category') } }
      %dl.half
        %dt= f.label :vendor, t('vinus.vendors.vendors')
        %dd= f.collection_select :vendor_id, Vinus::Vendor.with_translations(I18n.locale), :id, :name, {:prompt =>  t('vinus.vendors.choose_vendor')}, {:class => 'chosen', :multiple => false, :data => {:placeholder => t('vinus.vendors.choose_vendor') } }

    .clearfix

    .splitContainer
      %dl.third
        %dt= f.label :name, t('vinus.products.name')
        %dd= f.text_field :name, :class => 'text focus', :required => true
      %dl.third
        %dt= f.label :permalink, t('vinus.products.permalink')
        %dd= f.text_field :permalink, :class => 'text'
      %dl.third
        %dt= f.label :sku, t('vinus.products.sku')
        %dd= f.text_field :sku, :class => 'text', :required => true
    %dl
      %dt= f.label :description, t('vinus.products.description')
      %dd= f.text_area :description, :class => 'text', :required => true
    %dl
      %dt= f.label :short_description, t('vinus.products.short_description')
      %dd= f.text_area :short_description, :class => 'text', :required => true
    %dl
      %dt= f.label :in_the_box, t('vinus.products.in_the_box')
      %dd= f.text_area :in_the_box, :class => 'text'

  = field_set_tag t('vinus.products.attributes') do
    .margin
      %table.productAttributes
        %thead
          %tr
            %td= t('vinus.products.name')
            %td= t('vinus.products.value')
            %td.searchable= t('vinus.products.searchable?')
            %td.searchable= t('vinus.products.public?')
            %td.remove= t('vinus.products.remove')
            %td
        %tbody
          %tr.template{:style => 'display:none;'}
            %td= text_field_tag 'product[product_attributes_array][][key]', '', :placeholder => t('vinus.products.name')
            %td= text_field_tag 'product[product_attributes_array][][value]', '', :placeholder => t('vinus.products.value')
            %td.searchable= check_box_tag 'product[product_attributes_array][][searchable]', '1'
            %td.searchable= check_box_tag 'product[product_attributes_array][][public]', '1'
            %td.remove= link_to t('vinus.remove') , '#', :class => 'button button-mini purple'
            %td.handle
          - for attribute in @product.product_attributes
            %tr
              %td= text_field_tag 'product[product_attributes_array][][key]', attribute.key, :placeholder => t('vinus.products.name')
              %td= text_field_tag 'product[product_attributes_array][][value]', attribute.value, :placeholder => t('vinus.products.value')
              %td.searchable= check_box_tag 'product[product_attributes_array][][searchable]', '1', attribute.searchable?
              %td.searchable= check_box_tag 'product[product_attributes_array][][public]', '1', attribute.public?
              %td.remove= link_to t("vinus.remove"), '#', :class => 'button button-mini purple'
              %td.handle
      %p.addAttribute= link_to t('vinus.products.add_attribute') , '#', :data => {:behavior => 'addAttributeToAttributesTable'}, :class => 'button button-mini green'

  = field_set_tag t('vinus.products.attachments') do
    .splitContainer
      %dl.half
        %dt= f.label "attachments[default_image][file]", t('vinus.products.default_image')
        %dd
          = attachment_preview @product.default_image
          %p= f.file_field "attachments[default_image][file]"
          = f.hidden_field "attachments[default_image][role]", value: "default_image"
          = f.hidden_field "attachments[default_image][parent_id]", value: @product.id
      %dl.half
        %dt= f.label "attachments[data_sheet][file]", t('vinus.products.datasheet')
        %dd
          = attachment_preview @product.data_sheet
          %p= f.file_field "attachments[data_sheet][file]"
          = f.hidden_field "attachments[data_sheet][role]", value: "data_sheet"
          = f.hidden_field "attachments[data_sheet][parent_id]", value: @product.id

    .splitContainer.extraAttachments
      %dl.half
        %dd
          = attachment_preview nil, hide_if_blank: false
          %p= f.file_field "attachments[extra][file]", :multiple => true
          = f.hidden_field "attachments[extra][parent_type]", value: "Vinus::Product"
          = f.hidden_field "attachments[extra][parent_id]", value: @product.id

      - @product.attachments.each do |attachment|
        - unless ["default_image", "data_sheet"].include?(attachment.role)
          %dl.half
            %dd
              = attachment_preview attachment

    %p.addAttachments= link_to t('vinus.products.add_attachments') , '#', :data => {:behavior => 'addAttachmentToExtraAttachments'}, :class => 'button button-mini green'

  - unless @product.has_variants?
    = field_set_tag t('vinus.products.pricing') do
      .splitContainer
        %dl.third
          %dt= f.label :price, t('vinus.products.price')
          %dd
            .moneyInput
              .currency= Vinus.settings.currency_unit.html_safe
              = f.text_field :price, :class => 'text'
        %dl.third
          %dt= f.label :cost_price, t('vinus.products.cost_price')
          %dd
            .moneyInput
              .currency= Vinus.settings.currency_unit.html_safe
              = f.text_field :cost_price, :class => 'text'
        %dl.third
          %dt= f.label :tax_rate_id, t('vinus.products.tax_rate')
          %dd= f.collection_select :tax_rate_id, Vinus::TaxRate.ordered, :id, :description, {:include_blank => true}, {:class => 'chosen-with-deselect', :data => {:placeholder => t('vinus.products.no_tax')}}

    = field_set_tag  t('vinus.products.stock_control') do
      .splitContainer
        %dl.half
          %dt= f.label :weight, t('vinus.products.weight')
          %dd= f.text_field :weight, :class => 'text'

        %dl.half
          %dt= f.label :stock_control,  t('vinus.products.stock_control')
          %dd.checkbox
            = f.check_box :stock_control
            = f.label :stock_control, t('vinus.products.enable_stock_control?')

  = field_set_tag  t('vinus.products.website_properties') do
    .splitContainer
      %dl.half
        %dt= f.label :active,  t('vinus.products.on_sale?')
        %dd.checkbox
          = f.check_box :active
          = f.label :active,  t('vinus.products.on_sale_info')
      %dl.half
        %dt= f.label :featured,  t('vinus.products.featured?')
        %dd.checkbox
          = f.check_box :featured
          = f.label :featured, t('vinus.products.featured_info')

  %p.submit
    - unless @product.new_record?
      %span.right= link_to t('vinus.delete') , @product, :class => 'button purple', :method => :delete, :data => {:confirm => "Are you sure you wish to remove this product?"}
    = f.submit t('vinus.submit'),  :class => 'button green'
    = link_to t('vinus.cancel'), :products, :class => 'button'

app/views/vinus/products/_table.html.haml
.table
  %table.data
    %thead
      %tr
        %th{:width => '20%'}
          = form_tag(:products, method: "get") do
            = t('vinus.products.sku')
            = search_field_tag :sku, params[:sku], size: 25, min: 2, placeholder: t('vinus.products.filter.sku')
        %th{:width => '40%'}
          = form_tag(:products, method: "get") do
            = t('vinus.products.name')
            = search_field_tag :name, params[:name], size: 65, min: 3, placeholder: t('vinus.products.filter.name_or_description')
        %th{:width => '25%'}= t('vinus.products.price_variants')
        %th{:width => '15%'}= t('vinus.products.stock')
      %tr
        %th
        %th(colspan='3')
          = t('vinus.product_category.product_categories')
          - options = options_for_select(nested_set_options(Vinus::ProductCategory) {|i| "#{'-' * i.level} #{i.name}" }, params[:category_id] )
          = select_tag 'parent_id', options, { onchange: "window.location.href='#{products_url}/?category_id=' + $(this).val() + ''"}
    %tbody
      - if products.empty?
        %tr.empty
          %td{:colspan => 4}= t('vinus.products.no_products')
      - else
        - for category, products in products
          %tr
            %th{:colspan => 4}= category.name
          - for product in products
            %tr
              %td= product.sku
              %td= link_to product.name, [:edit, product]
              - if product.has_variants?
                %td.table{:colspan => 2}
                  %table.data
                    - for variant in product.variants
                      %tr
                        %td{:width => '40%'}= link_to variant.name, edit_product_variant_path(product, variant)
                        %td{:width => '30%'}= number_to_currency variant.price
                        %td{:width => '30%'}
                          - if variant.stock_control?
                            %span.float-right= link_to t('vinus.products.edit') , stock_level_adjustments_path(:item_type => variant.class, :item_id => variant.id), :class => 'edit', :rel => 'dialog', :data => {:dialog_width => 700, :dialog_behavior => 'stockLevelAdjustments'}
                            = boolean_tag(variant.in_stock?, nil, :true_text => variant.stock, :false_text => t('vinus.products.no_stock'))
                          - else
                            &#8734;
              - else
                %td= number_to_currency product.price
                %td
                  - if product.stock_control?
                    %span.float-right= link_to t('vinus.products.edit'), stock_level_adjustments_path(:item_type => product.class, :item_id => product.id), :class => 'edit', :rel => 'dialog', :data => {:dialog_width => 700, :dialog_behavior => 'stockLevelAdjustments'}
                    = boolean_tag(product.in_stock?, nil, :true_text => product.stock, :false_text => t('vinus.products.no_stock'))
                  - else
                    &#8734;

app/views/vinus/products/edit.html.haml
- @page_title = t('vinus.products.products')
= content_for :header do
  %p.buttons
    = link_to t('vinus.localisations.localisations') , [@product, :localisations], :class => 'button'
    = link_to t('vinus.products.variants') , [@product, :variants], :class => 'button'
    = link_to t('vinus.products.stock_levels') , stock_level_adjustments_path(:item_id => @product.id, :item_type => @product.class), :class => 'button', :rel => 'dialog', :data => {:dialog_width => 700, :dialog_behavior => 'stockLevelAdjustments'}
    = link_to t('vinus.products.back_to_products') , :products, :class => 'button'
  %h2.products= t('vinus.products.products')
= render 'form'

app/views/vinus/products/import.html.haml
- @page_title = t('vinus.products.products')

= content_for :header do
  %h2.products= t('vinus.products.import_products')

= form_for "import", :url => import_products_path, :html => {:multipart => true} do |f|
  = f.error_messages

  = field_set_tag t('vinus.imports.file_upload') do
    %dl
      %dt= f.label :import_file, t('vinus.imports.required_formats')
      %dd= f.file_field :import_file

  = field_set_tag t('vinus.imports.example_file') do
    %dl
      %dd
        %table.importExample
          %thead
            %tr
              %th name
              %th sku
              %th permalink
              %th description
              %th short_description
              %th weight
              %th price
              %th category_name
              %th qty
          %tbody
            %tr
              %td= t('vinus.products.imports.examples.first.name')
              %td= t('vinus.products.imports.examples.first.sku')
              %td= t('vinus.products.imports.examples.first.permalink')
              %td= t('vinus.products.imports.examples.first.description')
              %td= t('vinus.products.imports.examples.first.short_description')
              %td= t('vinus.products.imports.examples.first.weight')
              %td= t('vinus.products.imports.examples.first.price')
              %td= t('vinus.products.imports.examples.first.category_name')
              %td= t('vinus.products.imports.examples.first.qty')
            %tr
              %td= t('vinus.products.imports.examples.second.name')
              %td= t('vinus.products.imports.examples.second.sku')
              %td= t('vinus.products.imports.examples.second.permalink')
              %td= t('vinus.products.imports.examples.second.description')
              %td= t('vinus.products.imports.examples.second.short_description')
              %td= t('vinus.products.imports.examples.second.weight')
              %td= t('vinus.products.imports.examples.second.price')
              %td= t('vinus.products.imports.examples.second.category_name')
              %td= t('vinus.products.imports.examples.second.qty')
            %tr
              %td= t('vinus.products.imports.examples.third.name')
              %td= t('vinus.products.imports.examples.third.sku')
              %td= t('vinus.products.imports.examples.third.permalink')
              %td= t('vinus.products.imports.examples.third.description')
              %td= t('vinus.products.imports.examples.third.short_description')
              %td= t('vinus.products.imports.examples.third.weight')
              %td= t('vinus.products.imports.examples.third.price')
              %td= t('vinus.products.imports.examples.third.category_name')
              %td= t('vinus.products.imports.examples.third.qty')
            %tr.tear-off
              %td{:colspan => "8"}
      %dd
        %p.help= t('vinus.products.imports.help')

  %p.submit
    = f.submit t('vinus.import'), :class => "button green"
    = link_to t('vinus.cancel'), :products, :class => "button"

app/views/vinus/products/new.html.haml
- @page_title = t('vinus.products.products')

= content_for :header do
  %p.buttons= link_to t('vinus.products.back_to_products') , :products, :class => 'button'
  %h2.products= t('vinus.products.products')

= render 'form'